# Generated by Django 5.2.3 on 2025-06-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internationalSwelfare', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostel',
            old_name='capacity',
            new_name='empty_slots',
        ),
        migrations.AddField(
            model_name='hostel',
            name='price_per_month',
            field=models.DecimalField(decimal_places=2, default=123, max_digits=8),
            preserve_default=False,
        ),
    ]
