# Generated by Django 5.2.3 on 2025-07-07 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internationalSwelfare', '0003_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
    ]
